{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fastverse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastverse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastverse/fastverse_{{ version }}.tar.gz
  sha256: 10cac29096c4f2e1b915cafaffb2553339e0f2accaafa96e076fbfc5fede4fc4

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-collapse
    - r-data.table
    - r-fst
    - r-kit
    - r-magrittr
    - r-matrixstats
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-collapse
    - r-data.table
    - r-fst
    - r-kit
    - r-magrittr
    - r-matrixstats

test:
  commands:
    - $R -e "library('fastverse')"           # [not win]
    - "\"%R%\" -e \"library('fastverse')\""  # [win]

about:
  home: https://sebkrantz.github.io/fastverse/, https://github.com/SebKrantz/fastverse
  license: GPL-3.0-only
  summary: "Easy installation, loading and management, of a complementary set of high-performance packages for statistical computing and data manipulation. The core 'fastverse' consists of 6 packages: 'data.table', 'collapse', 'matrixStats', 'kit', 'magrittr' and 'fst', that jointly only depend on 'Rcpp'. These packages\
    \ are attached and harmonized through the 'fastverse'. In addition, the 'fastverse' can be freely and permanently extended with additional packages, both globally or for individual projects. Entirely separate package verses can also be created. Selected fast and low-dependency packages are suggested for various topics\
    \ such as time series, dates and times, strings, spatial data, statistics and data serialization (see GitHub / website)."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - SebKrantz

# Package: fastverse
# Title: A Suite of High-Performance Packages for Statistics and Data Manipulation
# Version: 0.2.3
# Authors@R: c(person("Sebastian", "Krantz", role = c("aut", "cre"), email = "sebastian.krantz@graduateinstitute.ch"), person("Hadley", "Wickham", role = "ctb"))
# Description: Easy installation, loading and management, of a complementary set of high-performance packages for statistical computing and data manipulation. The core 'fastverse' consists of 6 packages: 'data.table', 'collapse', 'matrixStats', 'kit', 'magrittr' and 'fst', that jointly only depend on 'Rcpp'. These packages are attached and harmonized through the 'fastverse'. In addition, the 'fastverse' can be freely and permanently extended with additional packages, both globally or for individual projects. Entirely separate package verses can also be created. Selected fast and low-dependency packages are suggested for various topics such as time series, dates and times, strings, spatial data, statistics and data serialization (see GitHub / website).
# License: GPL-3
# Encoding: UTF-8
# Imports: data.table, collapse, matrixStats, kit, magrittr, fst
# Suggests: xts, roll, fasttime, lubridate, dygraphs, stringi, stringfish, Rfast, Rfast2, coop, rrapply, qs, tidyfast, maditr, knitr, rmarkdown
# URL: https://sebkrantz.github.io/fastverse/, https://github.com/SebKrantz/fastverse
# BugReports: https://github.com/SebKrantz/fastverse/issues
# RoxygenNote: 7.1.2
# NeedsCompilation: yes
# VignetteBuilder: knitr
# Packaged: 2022-02-17 10:57:58 UTC; Sebastian Krantz
# Author: Sebastian Krantz [aut, cre], Hadley Wickham [ctb]
# Maintainer: Sebastian Krantz <sebastian.krantz@graduateinstitute.ch>
# Repository: CRAN
# Date/Publication: 2022-02-17 13:02:06 UTC
